# Generated by Django 6.0.6 on 2026-06-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo de consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'consulta médica',
                'verbose_name_plural': 'consultas médicas',
                'ordering': ['-fecha'],
            },
        ),
    ]
