# Generated by Django 6.0.6 on 2026-06-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial', '0001_initial'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='mascotas.mascota', verbose_name='Mascota'),
        ),
    ]
