# Generated by Django 6.0.3 on 2026-06-20 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_initial'),
        ('mascotas', '0003_mascota_token_collar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hc', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° HC')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada')], default='activa', max_length=10, verbose_name='Estado')),
                ('propietario_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('propietario_documento', models.CharField(blank=True, max_length=20, verbose_name='Documento')),
                ('propietario_direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('propietario_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('propietario_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('paciente_sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('N', 'No especificado')], default='N', max_length=1, verbose_name='Sexo')),
                ('paciente_color_pelaje', models.CharField(blank=True, max_length=100, verbose_name='Color / Pelaje')),
                ('paciente_microchip', models.CharField(blank=True, max_length=50, verbose_name='N° Microchip')),
                ('paciente_procedencia', models.CharField(blank=True, max_length=200, verbose_name='Procedencia')),
                ('paciente_fin_zootecnico', models.CharField(blank=True, max_length=100, verbose_name='Fin zootécnico')),
                ('paciente_senas_particulares', models.TextField(blank=True, verbose_name='Señas particulares')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('dieta', models.CharField(blank=True, max_length=300, verbose_name='Dieta')),
                ('enfermedades_previas', models.TextField(blank=True, verbose_name='Enfermedades previas')),
                ('medicacion_actual', models.TextField(blank=True, verbose_name='Medicación actual')),
                ('cirugias_previas', models.TextField(blank=True, verbose_name='Cirugías previas')),
                ('vacunacion', models.TextField(blank=True, verbose_name='Vacunación')),
                ('desparasitacion', models.TextField(blank=True, verbose_name='Desparasitación')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='Esterilizado/a')),
                ('partos', models.TextField(blank=True, verbose_name='Partos')),
                ('observaciones_anamnesis', models.TextField(blank=True, verbose_name='Observaciones')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True, verbose_name='FC (lpm)')),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='FR (rpm)')),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso actual (kg)')),
                ('diagnostico_presuntivo', models.TextField(blank=True, verbose_name='Diagnóstico presuntivo')),
                ('diagnostico_definitivo', models.TextField(verbose_name='Diagnóstico definitivo')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('medicacion_prescrita', models.TextField(blank=True, verbose_name='Medicación prescrita')),
                ('observaciones_clinicas', models.TextField(blank=True, verbose_name='Observaciones clínicas')),
                ('proxima_visita', models.DateField(blank=True, null=True, verbose_name='Próxima visita')),
                ('evolucion', models.TextField(blank=True, verbose_name='Evolución')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas', to='mascotas.mascota', verbose_name='Mascota')),
                ('veterinario_responsable', models.ForeignKey(blank=True, limit_choices_to={'rol': 'veterinario'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historias_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario responsable')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
