# Generated by Django 6.0.4 on 2026-06-15 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(max_length=255, verbose_name='ID de preferencia MP')),
                ('payment_id', models.CharField(blank=True, max_length=255, verbose_name='ID de pago MP')),
                ('estado_mp', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('in_process', 'En proceso')], default='pending', max_length=20, verbose_name='Estado en MP')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_mp', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'pago Mercado Pago',
                'verbose_name_plural': 'pagos Mercado Pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
