# Generated by Django 6.0.3 on 2026-06-21 13:42

import apps.adopciones.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotaadopcion',
            name='refugio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Refugio/Organización'),
        ),
        migrations.AddField(
            model_name='mascotaadopcion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ubicación'),
        ),
        migrations.CreateModel(
            name='FotoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=apps.adopciones.models.ruta_foto_galeria, verbose_name='Foto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionales', to='adopciones.mascotaadopcion', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'foto adicional',
                'verbose_name_plural': 'fotos adicionales',
                'ordering': ['orden'],
            },
        ),
    ]
