# Generated by Django 6.0.6 on 2026-06-07 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='veterinario',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario'),
        ),
    ]
