# Generated by Django 6.0.3 on 2026-06-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo_consulta',
            field=models.CharField(choices=[('consulta_general', 'Consulta general'), ('vacunacion', 'Vacunación'), ('control', 'Control'), ('urgencia', 'Urgencia'), ('cirugia', 'Cirugía')], default='consulta_general', max_length=20, verbose_name='Tipo de consulta'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CambioEstadoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado nuevo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_turno', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='turnos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'cambio de estado de turno',
                'verbose_name_plural': 'cambios de estado de turnos',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
