# Generated by Django 6.0.6 on 2026-06-07 03:49

import apps.mascotas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('otro', 'Otro')], max_length=20, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('fecha_nacimiento', models.DateField(validators=[apps.mascotas.models.validar_fecha_no_futura], verbose_name='Fecha de nacimiento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.mascotas.models.ruta_foto_mascota, verbose_name='Foto')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['nombre'],
            },
        ),
    ]
