# Generated by Django 6.0.6 on 2026-06-07 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(limit_choices_to={'rol': 'dueno'}, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Dueño'),
        ),
    ]
